### PR TITLE
Draft: Add compatibility with macOS

### PR DESCRIPTION
**Pull request by claucambra**
Hi all,

On the desktop client we'd like to implement a similar feature to the iOS client's File Provider API, which uses this library. This PR contains changes that should let the client build on macOS as well as iOS

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@claucambra thanks for this PR, have you tested the library with MacOS ? For now we use it only with iOS but your contribute for Mac OS will be great !

**Comment by claucambra** [comment]
> @claucambra thanks for this PR, have you tested the library with MacOS ? For now we use it only with iOS but your contribute for Mac OS will be great !

The build works but these changes do ned some testing on the macOS client, for now we are still figuring out how to do the painful process of getting the Qt app to communicate with the extension. Hopefully we can transplant a lot of the file provider stuff from the iOS client to the desktop app with not much pain :)

**Comment by marinofaggiana** [comment]
Good !! it would be better change the name of library ... @Ivansss @thisIsTheFoxe what's do you think ?

**Comment by Ivansss** [comment]
> Good !! it would be better change the name of library

I guess it would make sense to change the library name if the library is going to be used in macOS as well :)

**Comment by thisIsTheFoxe** [comment]
> it would be better change the name of library

I mean in general, yea, we can do it.. but I'm not sure if it's used apart from @Nextcloud..? thinking if it would cause SPM to fail if anyone uses it.. but then again it does say **BETA** right there in the readme.. :D

**Comment by marinofaggiana** [comment]
Or we can "Archive" for 6 month this repository (after we can remove it) and create a new ... 

Name, proposal : 

- Nextcloud SDK for Apple : nexcloud-sdk-apple .. or ?

**Comment by claucambra** [comment]
> Or we can "Archive" for 6 month this repository (after we can remove it) and create a new ...
> 
> Name, proposal :
> 
> * Nextcloud SDK for Apple : NextcloudSDKApple .. or ?

...or NextcloudKit :)

**Comment by marinofaggiana** [comment]
I like the NextcloudKit,  I thing we need change also  the name also in NextcloudKit (NCCommunication) @thisIsTheFoxe ?

**Comment by marinofaggiana** [comment]
Hi @claucambra what's the status here ? can you informed me ?

**Comment by claucambra** [comment]
Hi @marinofaggiana, actively working with this branches' changes now but still haven't tested it fully. I'll have updates next week :)

**Comment by marinofaggiana** [comment]
Ok, thanks!, ping me when ready :)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/NextcloudKit

**Pull request closed without merging**
