### PR TITLE
Refactor NCCError & error handling

### LINKED ISSUE #1172: Share Password complex - error message
When sharing a file with a password and complex password requirement is not met, the error displayed is very generic and non-descriptive which is not very intuitive for the end user.

Could this be changed to show that the "password does not meet the complexity criteria"

### LINKED ISSUE #1706: Password Folder Sharing Connection was lost
### Steps to reproduce

1. Share a folder
2. Add password that dose not meet the complexity 
3. Getting network connection error

### Expected behavior

The ios app should inform the user that the password dose not meet the complexity set by the admin or its a common password and redirect them back to the password page to try a different password or have the app automatically generate a complex password and let the user copy it so they can share it 

### Actual behavior

Getting The network connection was lost and if you in put a password that dose not meet the complaxity it'll throw this error again. The user will never know what the issue is. 

### Logs

```
Exception: Password is among the 1,000,000 most common ones. Please make it unique. Password needs to be at least 8 characters long. Password needs to contain at least one special character. Password is present in compromised password list. Please choose a different password.
```

### Reasoning or why should it be changed/implemented?
So the username knows why the share is not being shared and get a specific error 
### Environment data

**iOS version:** e.g. iOS 14.4.1
15.0.1
**Nextcloud iOS app version:** see More > Settings
4.0.6.0
**Server operating system:**
Ubuntu 20.4
**Web server:** Apache, nginx
Apache 2
**Database:**
Maraia DB
**PHP version:**
PHP 8
**Nextcloud version:** see Nextcloud admin page
22.2.0

### LINKED ISSUE #1792: Sharing - Undefined error message appears when entering an insecure password
Frequency
Every Time

Actions Performed
1. Open the app
2. Click on the person-icon next to any file
3. Click on "shortcut" erstellen
4. Click on the 3 dots next to the link
5. Open the advanced permissions section
6. Toggle the password section and enter any insecure password
7. Click on "Accept"

Expected Result
Either it should be possible to protect the file with an insecure password or a corresponding appropriate message should appear

Actual Result
Undefined error message appears when entering an insecure password without explaining why

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Motivation is that often an error message is included in the ocs data but is often ignored and it only shows the general http error description. This PR gives preference to OCS errors over http errors, if one exists.
Also, a general refactorization will (hopefully) help to improve code quality and clarity and make it easier to maintain it in the future. :rocket:

 - Fixes https://github.com/nextcloud/ios/issues/1792
 - Fixes https://github.com/nextcloud/ios/issues/1706
 - Fixes nextcloud/ios#1172
 - https://github.com/nextcloud/ios/issues/1777
 - https://github.com/nextcloud/ios/issues/1806

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe this can be good, but required entire refactoring of Nextcloud & Talk .... [error: NCCError -> for me is better NCCommunicationError or NCCommunication+Error]. Maybe possible but required a coordination between us all @thisIsTheFoxe @Ivansss @alazarevic5 for a PR -> Approved very speed because touches all parts of the two programs

**Review by Ivansss — APPROVED** [review]
The PR looks good 👍
As @marinofaggiana said this will require some refactoring in the Talk iOS app (and in the Nextcloud iOS app), but since this PR fixes the problems that @thisIsTheFoxe mentioned in the first comment, I would go for it.

**Review by aleksandralazarevic — APPROVED** [review]

**Comment by marinofaggiana** [comment]
We can merge ONLY when we are ready for modify the app. thanks

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/NextcloudKit

**Pull request closed without merging**
