### PR TITLE
Fix string URL encoding

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Fixes https://github.com/nextcloud/ios/issues/1819
Fixes: https://github.com/nextcloud/ios/issues/1843

Todo:
- [x] Test

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Hi @thisIsTheFoxe thanks for this PR do you have tested with all API (we have had huge problems in the past) the encoding is several dangerous... is tested with **all** API  ?

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana I tested it a lot.. but as you said you use the same function a lot throughout the codebase. Feel free to have another look over it and let me know you find anything.

For reference: [Try it online!](https://tio.run/##hVRRb9owEH7Pr7iajiaFGnVUVZdC6USHNGmbtlKegAcTLsWScZDjlE0dv53ZJKEEUnYPkWN/933f3VmOlzzUV@s1ny8ipaEXJXLKNI@k4zj4W6OMzRq6M6ZYoFH1UcOrAybCRAbAhBhIHkRT7AdMMBW7HlzcwbCwOc4ybLwwBQrjRGj/ANWG4XgLDCMFC8EkApeQAengqXdDu2ZlNjSdc0kpvbyG5QwVQowipDMWf8f5BJXL5U@b7qcs3o6HnD5JWfcEmh@3Cm6W2mqBUaG0dRQHNbjMsUUxGzwEYXpnNG0vTa2F4t3Mi1dPywgiqRmXsZvhvRJGG2krKVssUE634APoyin/e1sp1ImSGZ@Tnq3MFbCeWTh4/PYrQfXnsxDREqd@8T60d8xZ/DNKVEw8oOBzbjDxU/RFbjrdBuJXhuN7Ao0GTCOMQUba9D8QiTklHQJmLKRBYJog6Agee11ofrq5hgvoY2BvJTTpVUEsTiblQien1TPXO6/Vb9ukkIEWwiYC3/IMfrciN8h/4q/SBzJy3y3JG7mlDjziOfvN3ZWgiRK7LaWGRdtTLp/dEofpTFeul45kwmLcM73PuMFJXJrZZTv/SShYGJIaqQOp2k@HjDPZjTHcGz6Bym3nvto@rb2uWnf1k7Pzvx9IenFS4j38kU4f8nuUyxdU2tTjLBSX2iXGdn4PjbtChbTkPfLyPNvASjHs1kg@8DA0D4gM0LdTy@A/omVewKHObqtKqvSOGrHMaaUb5pL8An9B@R3m9fof "Swift – Try It Online")

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe , try:

Create a directory with name 0"
Upload a file inside 0"

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana I did. Works fine both locally and on c.nc.c
Also, again I'm not sure why the branch was changed automatically..? Maybe because of #108

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe do you have make a test indire a directory with the double quotes ?
example dir: blabla" <- double quotes

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana I tested it with the string you mentioned before `0"` and was able to create files within that directory as expected.

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe will be another test for security

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe Seems works !

**Pull request merged**
